# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VLBI Group
email: jlgomez@iaa.es
description: Our research group is focused on the study of black hole accretion and relativistic jet formation through very long baseline interferometric observations (VLBI) with mm-wave arrays, such as the Event Horizon Telescope (EHT), orbiting antennas, such as the space VLBI mission RadioAstron, and long-term monitoring programs such as MOJAVE and VLBA-BU-BLAZAR.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

